name: king_saud_hospital
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  easy_localization: ^3.0.2
  flutter_phoenix: ^1.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.4
  shared_preferences: ^2.0.20
  get_it: ^7.2.0
  go_router: ^9.0.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  pin_code_fields: ^8.0.1
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  fluttertoast: ^8.2.2
  animate_do: ^3.0.2
  dotted_border: ^2.0.0+3
  connectivity_plus: ^4.0.2
  carousel_slider: ^4.2.1
  easy_stepper: ^0.7.3
  flutter_html: ^3.0.0-beta.2
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  intl:
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdfviewer: ^23.1.40
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  url_launcher: ^6.1.14



dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/images/
    - assets/svg/
    - assets/pdf/
    - assets/images/sponsors/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json


  # example:
  fonts:
    - family: expo-bold
      fonts:
        - asset: assets/fonts/expo-arabic-bold.ttf
          style: italic
    - family: expo-book
      fonts:
        - asset: assets/fonts/expo-arabic-book.ttf
          style: italic
    - family: expo-medium
      fonts:
        - asset: assets/fonts/expo-arabic-medium.ttf
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
